<template>
  <div class="intro-page">
    <div class="intro-content">
      <div class="lines-wrapper"></div>
      <h1 class="animated-title">
        <span class="word word-1">
          <span class="letter letter-1 focus-in-expand">T</span>
          <span class="letter letter-2 focus-in-expand">h</span>
          <span class="letter letter-3 focus-in-expand">e</span>
        </span>
        <span class="word word-2">
          <span class="letter letter-4 focus-in-expand">C</span>
          <span class="letter letter-5 focus-in-expand">o</span>
          <span class="letter letter-6 focus-in-expand">f</span>
          <span class="letter letter-7 focus-in-expand">f</span>
          <span class="letter letter-8 focus-in-expand">e</span>
          <span class="letter letter-9 focus-in-expand">e</span>
        </span>
        <span class="word word-3">
          <span class="letter letter-10 focus-in-expand">H</span>
          <span class="letter letter-11 focus-in-expand">o</span>
          <span class="letter letter-12 focus-in-expand">u</span>
          <span class="letter letter-13 focus-in-expand">s</span>
          <span class="letter letter-14 focus-in-expand">e</span>
        </span>
      </h1>
      <p class="subtitle fade-in">Welcome to our coffee experience</p>

      <!-- Animated circular button -->
      <button class="enter-button bounce-in" @click="goToHome">
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <line x1="5" y1="12" x2="19" y2="12"></line>
          <polyline points="12 5 19 12 12 19"></polyline>
        </svg>
      </button>
    </div>
  </div>
</template>

<script>
import { useRouter } from "vue-router";

export default {
  name: "IntroPage",
  setup() {
    const router = useRouter();

    const goToHome = () => {
      router.push("/");
    };

    return {
      goToHome,
    };
  },
};
</script>

<style scoped>
.intro-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: white;
  overflow: hidden;
  perspective: 1000px;
}

.intro-content {
  text-align: center;
  padding: 40px;
}

.lines-wrapper {
  width: 90%;
  height: 90%;
  position: absolute;
  top: 5%;
  left: 5%;
  overflow: hidden;
  box-sizing: border-box;
  border: 1px solid #666;
}

.animated-title {
  font-size: 9rem;
  font-weight: 500;
  margin: 0;
  display: flex;
  gap: 1.5rem;
  justify-content: center;
  flex-wrap: wrap;
  font-family: "HelveticaNeue-Light", "HelveticaNeue", Helvetica, "Roboto-Thin",
    Arial, sans-serif-light;
  letter-spacing: 0.05em;
}

.word {
  display: inline-flex;
  color: rgb(62, 62, 62);
}

.letter {
  display: inline-block;
}

/* Staggered animation delays for each letter */
.letter-1 {
  animation-delay: 0.05s;
}
.letter-2 {
  animation-delay: 0.1s;
}
.letter-3 {
  animation-delay: 0.15s;
}
.letter-4 {
  animation-delay: 0.2s;
}
.letter-5 {
  animation-delay: 0.25s;
}
.letter-6 {
  animation-delay: 0.3s;
}
.letter-7 {
  animation-delay: 0.35s;
}
.letter-8 {
  animation-delay: 0.4s;
}
.letter-9 {
  animation-delay: 0.45s;
}
.letter-10 {
  animation-delay: 0.5s;
}
.letter-11 {
  animation-delay: 0.55s;
}
.letter-12 {
  animation-delay: 0.6s;
}
.letter-13 {
  animation-delay: 0.65s;
}
.letter-14 {
  animation-delay: 0.7s;
}

.focus-in-expand {
  animation: focus-in-expand 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-12-11 10:58:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0);
    opacity: 1;
  }
}

/* Subtitle fade in animation */
.subtitle {
  font-size: 1.8rem;
  color: #666;
  margin-top: 2rem;
  opacity: 0;
  font-family: familyTeXGyreAdventorRegular;
}

.fade-in {
  animation: fadeIn 1s ease-in 1.5s forwards;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Animated circular button */
.enter-button {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  border: 2px solid rgb(62, 62, 62);
  background: #3e3e3e;
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 8rem auto 0;
  transition: all 0.3s ease;
  opacity: 0;
}

.enter-button:hover {
  background: white;
  color: #3e3e3e;
  transform: scale(1.1);
  box-shadow: 0 8px 20px rgba(62, 62, 62, 0.3);
}

/* Bounce in animation for button */
.bounce-in {
  animation: bounceIn 0.8s cubic-bezier(0.68, -0.55, 0.265, 1.55) 2s forwards;
}

@keyframes bounceIn {
  0% {
    opacity: 0;
    transform: scale(0.3) translateY(-50px);
  }
  50% {
    opacity: 1;
    transform: scale(1.05);
  }
  70% {
    transform: scale(0.9);
  }
  100% {
    opacity: 1;
    transform: scale(1);
  }
}

/* Responsive */
@media (max-width: 768px) {
  .animated-title {
    font-size: 3rem;
    gap: 1rem;
  }

  .subtitle {
    font-size: 1.2rem;
  }
}

@media (max-width: 480px) {
  .animated-title {
    font-size: 2rem;
    gap: 0.8rem;
  }

  .subtitle {
    font-size: 1rem;
  }
}
</style>
